/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gdface_sdk_fse_FseJniBridge */

#ifndef _Included_net_gdface_sdk_fse_FseJniBridge
#define _Included_net_gdface_sdk_fse_FseJniBridge
#ifdef __cplusplus
extern "C" {
#endif
#undef net_gdface_sdk_fse_FseJniBridge_DEFAULT_INITIAL_CAPACITY
#define net_gdface_sdk_fse_FseJniBridge_DEFAULT_INITIAL_CAPACITY 16777216L
#undef net_gdface_sdk_fse_FseJniBridge_DEFAULT_LOAD_FACTOR
#define net_gdface_sdk_fse_FseJniBridge_DEFAULT_LOAD_FACTOR 0.75f
#undef net_gdface_sdk_fse_FseJniBridge_DEFAULT_OVERBLOCK_CAPACITY
#define net_gdface_sdk_fse_FseJniBridge_DEFAULT_OVERBLOCK_CAPACITY 1024L
#undef net_gdface_sdk_fse_FseJniBridge_DEFAULT_MODE
#define net_gdface_sdk_fse_FseJniBridge_DEFAULT_MODE 0L
/*
 * Class:     net_gdface_sdk_fse_FseJniBridge
 * Method:    init
 * Signature: (IIFI)V
 */
JNIEXPORT void JNICALL Java_net_gdface_sdk_fse_FseJniBridge_init
  (JNIEnv *, jclass, jint, jint, jfloat, jint);

/*
 * Class:     net_gdface_sdk_fse_FseJniBridge
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gdface_sdk_fse_FseJniBridge_release
  (JNIEnv *, jclass);

/*
 * Class:     net_gdface_sdk_fse_FseJniBridge
 * Method:    searchCode
 * Signature: ([BDI[Ljava/lang/String;)[Lnet/gdface/sdk/fse/CodeBean;
 */
JNIEXPORT jobjectArray JNICALL Java_net_gdface_sdk_fse_FseJniBridge_searchCode
  (JNIEnv *, jclass, jbyteArray, jdouble, jint, jobjectArray);

/*
 * Class:     net_gdface_sdk_fse_FseJniBridge
 * Method:    getFeature
 * Signature: ([B)Lnet/gdface/sdk/fse/CodeBean;
 */
JNIEXPORT jobject JNICALL Java_net_gdface_sdk_fse_FseJniBridge_getFeature
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_gdface_sdk_fse_FseJniBridge
 * Method:    addFeature
 * Signature: ([B[BLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gdface_sdk_fse_FseJniBridge_addFeature
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jstring);

/*
 * Class:     net_gdface_sdk_fse_FseJniBridge
 * Method:    removeFeature
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gdface_sdk_fse_FseJniBridge_removeFeature
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_gdface_sdk_fse_FseJniBridge
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gdface_sdk_fse_FseJniBridge_size
  (JNIEnv *, jclass);

/*
 * Class:     net_gdface_sdk_fse_FseJniBridge
 * Method:    statInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gdface_sdk_fse_FseJniBridge_statInfo
  (JNIEnv *, jclass);
//JNIEXPORT jstring JNICALL Java_net_gdface_sdk_fse_FseJniBridge_md5
//(JNIEnv *env, jclass, jbyteArray input);
//JNIEXPORT jdouble JNICALL Java_net_gdface_sdk_fse_FseJniBridge_compare
//(JNIEnv *env, jclass, jbyteArray f1, jbyteArray f2);
#ifdef __cplusplus
}
#endif
#endif
