/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gdface_sdk_fse_FseJniBridge_CodeBean */

#ifndef _Included_net_gdface_sdk_fse_FseJniBridge_CodeBean
#define _Included_net_gdface_sdk_fse_FseJniBridge_CodeBean
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
